services:
  postgresDB:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"