version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: tabanok
    environment:
      POSTGRES_DB: tabanok
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
