import { MigrationInterface, QueryRunner } from "typeorm";

export class AddDiscountToRewardType1746568626232 implements MigrationInterface {
    name = 'AddDiscountToRewardType1746568626232'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TYPE "public"."reward_type_enum" RENAME TO "reward_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."reward_type_enum" AS ENUM('badge', 'points', 'achievement', 'cultural', 'experience', 'content', 'discount', 'exclusive_content', 'customization')`);
        await queryRunner.query(`ALTER TABLE "reward" ALTER COLUMN "type" TYPE "public"."reward_type_enum" USING "type"::"text"::"public"."reward_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reward_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."rewards_type_enum" RENAME TO "rewards_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."rewards_type_enum" AS ENUM('badge', 'points', 'achievement', 'cultural', 'experience', 'content', 'discount', 'exclusive_content', 'customization')`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "type" TYPE "public"."rewards_type_enum" USING "type"::"text"::"public"."rewards_type_enum"`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "type" SET DEFAULT 'badge'`);
        await queryRunner.query(`DROP TYPE "public"."rewards_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "isLimited" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "isLimited" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."tags_color_enum" RENAME TO "tags_color_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."tags_color_enum" AS ENUM('red', 'blue', 'green', 'yellow', 'purple', 'orange', 'pink', 'gray', 'brown')`);
        await queryRunner.query(`ALTER TABLE "tags" ALTER COLUMN "color" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tags" ALTER COLUMN "color" TYPE "public"."tags_color_enum" USING "color"::"text"::"public"."tags_color_enum"`);
        await queryRunner.query(`ALTER TABLE "tags" ALTER COLUMN "color" SET DEFAULT 'gray'`);
        await queryRunner.query(`DROP TYPE "public"."tags_color_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."notifications_type_enum" RENAME TO "notifications_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('achievement_unlocked', 'reward_earned', 'level_up', 'streak_milestone', 'cultural_content', 'system', 'new_message', 'mission_completed', 'collaboration_update')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "type" TYPE "public"."notifications_type_enum" USING "type"::"text"::"public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "user_levels" ALTER COLUMN "consistencyStreak" SET DEFAULT '{"current":0,"longest":0,"lastActivityDate":"2025-05-06T21:57:11.324Z"}'`);
        await queryRunner.query(`ALTER TYPE "public"."special_events_type_enum" RENAME TO "special_events_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."special_events_type_enum" AS ENUM('festival', 'ceremonia', 'encuentro', 'taller', 'competicion', 'exposicion')`);
        await queryRunner.query(`ALTER TABLE "special_events" ALTER COLUMN "type" TYPE "public"."special_events_type_enum" USING "type"::"text"::"public"."special_events_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."special_events_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."season_type_enum" RENAME TO "season_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."season_type_enum" AS ENUM('betscnate', 'jajan', 'bengbe_betsa', 'anteuan', 'flor_de_mayo', 'dia_grande')`);
        await queryRunner.query(`ALTER TABLE "season" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "season" ALTER COLUMN "type" TYPE "public"."season_type_enum" USING "type"::"text"::"public"."season_type_enum"`);
        await queryRunner.query(`ALTER TABLE "season" ALTER COLUMN "type" SET DEFAULT 'betscnate'`);
        await queryRunner.query(`DROP TYPE "public"."season_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."missions_type_enum" RENAME TO "missions_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."missions_type_enum" AS ENUM('COMPLETE_LESSONS', 'PRACTICE_EXERCISES', 'EARN_POINTS', 'MAINTAIN_STREAK', 'CULTURAL_CONTENT', 'COMMUNITY_INTERACTION', 'VOCABULARY', 'PERSONALIZED', 'PROGRESS_BASED', 'SEASONAL', 'COMMUNITY', 'LEARN_VOCABULARY', 'PARTICIPATE_FORUM')`);
        await queryRunner.query(`ALTER TABLE "missions" ALTER COLUMN "type" TYPE "public"."missions_type_enum" USING "type"::"text"::"public"."missions_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."missions_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."mentors_level_enum" RENAME TO "mentors_level_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."mentors_level_enum" AS ENUM('aprendiz', 'intermedio', 'avanzado', 'maestro', 'sabedor', 'basico')`);
        await queryRunner.query(`ALTER TABLE "mentors" ALTER COLUMN "level" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "mentors" ALTER COLUMN "level" TYPE "public"."mentors_level_enum" USING "level"::"text"::"public"."mentors_level_enum"`);
        await queryRunner.query(`ALTER TABLE "mentors" ALTER COLUMN "level" SET DEFAULT 'aprendiz'`);
        await queryRunner.query(`DROP TYPE "public"."mentors_level_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."mission_templates_type_enum" RENAME TO "mission_templates_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."mission_templates_type_enum" AS ENUM('COMPLETE_LESSONS', 'PRACTICE_EXERCISES', 'EARN_POINTS', 'MAINTAIN_STREAK', 'CULTURAL_CONTENT', 'COMMUNITY_INTERACTION', 'VOCABULARY', 'PERSONALIZED', 'PROGRESS_BASED', 'SEASONAL', 'COMMUNITY', 'LEARN_VOCABULARY', 'PARTICIPATE_FORUM')`);
        await queryRunner.query(`ALTER TABLE "mission_templates" ALTER COLUMN "type" TYPE "public"."mission_templates_type_enum" USING "type"::"text"::"public"."mission_templates_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."mission_templates_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."mission_templates_frequency_enum" RENAME TO "mission_templates_frequency_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."mission_templates_frequency_enum" AS ENUM('diaria', 'semanal', 'mensual', 'temporada', 'contribucion', 'unica')`);
        await queryRunner.query(`ALTER TABLE "mission_templates" ALTER COLUMN "frequency" TYPE "public"."mission_templates_frequency_enum" USING "frequency"::"text"::"public"."mission_templates_frequency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."mission_templates_frequency_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."cultural_achievements_category_enum" RENAME TO "cultural_achievements_category_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."cultural_achievements_category_enum" AS ENUM('lengua', 'danza', 'musica', 'artesania', 'historia', 'tradicion', 'gastronomia', 'medicina', 'rituales', 'mitos_leyendas')`);
        await queryRunner.query(`ALTER TABLE "cultural_achievements" ALTER COLUMN "category" TYPE "public"."cultural_achievements_category_enum" USING "category"::"text"::"public"."cultural_achievements_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."cultural_achievements_category_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."cultural_achievements_type_enum" RENAME TO "cultural_achievements_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."cultural_achievements_type_enum" AS ENUM('aprendizaje_cultural', 'exploracion_contenido', 'participacion_evento', 'creacion_contenido', 'contribucion_cultural', 'aprendizaje_lengua', 'dominio_cultural')`);
        await queryRunner.query(`ALTER TABLE "cultural_achievements" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cultural_achievements" ALTER COLUMN "type" TYPE "public"."cultural_achievements_type_enum" USING "type"::"text"::"public"."cultural_achievements_type_enum"`);
        await queryRunner.query(`ALTER TABLE "cultural_achievements" ALTER COLUMN "type" SET DEFAULT 'contribucion_cultural'`);
        await queryRunner.query(`DROP TYPE "public"."cultural_achievements_type_enum_old"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."cultural_achievements_type_enum_old" AS ENUM('participacion_evento', 'creacion_contenido', 'contribucion_cultural', 'aprendizaje_lengua', 'dominio_cultural')`);
        await queryRunner.query(`ALTER TABLE "cultural_achievements" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cultural_achievements" ALTER COLUMN "type" TYPE "public"."cultural_achievements_type_enum_old" USING "type"::"text"::"public"."cultural_achievements_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "cultural_achievements" ALTER COLUMN "type" SET DEFAULT 'contribucion_cultural'`);
        await queryRunner.query(`DROP TYPE "public"."cultural_achievements_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."cultural_achievements_type_enum_old" RENAME TO "cultural_achievements_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."cultural_achievements_category_enum_old" AS ENUM('lengua', 'danza', 'musica', 'artesania', 'historia', 'tradicion', 'gastronomia', 'medicina')`);
        await queryRunner.query(`ALTER TABLE "cultural_achievements" ALTER COLUMN "category" TYPE "public"."cultural_achievements_category_enum_old" USING "category"::"text"::"public"."cultural_achievements_category_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."cultural_achievements_category_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."cultural_achievements_category_enum_old" RENAME TO "cultural_achievements_category_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."mission_templates_frequency_enum_old" AS ENUM('diaria', 'semanal', 'mensual', 'temporada', 'contribucion')`);
        await queryRunner.query(`ALTER TABLE "mission_templates" ALTER COLUMN "frequency" TYPE "public"."mission_templates_frequency_enum_old" USING "frequency"::"text"::"public"."mission_templates_frequency_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."mission_templates_frequency_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."mission_templates_frequency_enum_old" RENAME TO "mission_templates_frequency_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."mission_templates_type_enum_old" AS ENUM('COMPLETE_LESSONS', 'PRACTICE_EXERCISES', 'EARN_POINTS', 'MAINTAIN_STREAK', 'CULTURAL_CONTENT', 'COMMUNITY_INTERACTION', 'VOCABULARY', 'PERSONALIZED', 'PROGRESS_BASED', 'SEASONAL', 'COMMUNITY')`);
        await queryRunner.query(`ALTER TABLE "mission_templates" ALTER COLUMN "type" TYPE "public"."mission_templates_type_enum_old" USING "type"::"text"::"public"."mission_templates_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."mission_templates_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."mission_templates_type_enum_old" RENAME TO "mission_templates_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."mentors_level_enum_old" AS ENUM('aprendiz', 'intermedio', 'avanzado', 'maestro', 'sabedor')`);
        await queryRunner.query(`ALTER TABLE "mentors" ALTER COLUMN "level" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "mentors" ALTER COLUMN "level" TYPE "public"."mentors_level_enum_old" USING "level"::"text"::"public"."mentors_level_enum_old"`);
        await queryRunner.query(`ALTER TABLE "mentors" ALTER COLUMN "level" SET DEFAULT 'aprendiz'`);
        await queryRunner.query(`DROP TYPE "public"."mentors_level_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."mentors_level_enum_old" RENAME TO "mentors_level_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."missions_type_enum_old" AS ENUM('COMPLETE_LESSONS', 'PRACTICE_EXERCISES', 'EARN_POINTS', 'MAINTAIN_STREAK', 'CULTURAL_CONTENT', 'COMMUNITY_INTERACTION', 'VOCABULARY', 'PERSONALIZED', 'PROGRESS_BASED', 'SEASONAL', 'COMMUNITY')`);
        await queryRunner.query(`ALTER TABLE "missions" ALTER COLUMN "type" TYPE "public"."missions_type_enum_old" USING "type"::"text"::"public"."missions_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."missions_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."missions_type_enum_old" RENAME TO "missions_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."season_type_enum_old" AS ENUM('betscnate', 'jajan', 'bengbe_betsa', 'anteuan')`);
        await queryRunner.query(`ALTER TABLE "season" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "season" ALTER COLUMN "type" TYPE "public"."season_type_enum_old" USING "type"::"text"::"public"."season_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "season" ALTER COLUMN "type" SET DEFAULT 'betscnate'`);
        await queryRunner.query(`DROP TYPE "public"."season_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."season_type_enum_old" RENAME TO "season_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."special_events_type_enum_old" AS ENUM('festival', 'ceremonia', 'encuentro', 'taller', 'competicion')`);
        await queryRunner.query(`ALTER TABLE "special_events" ALTER COLUMN "type" TYPE "public"."special_events_type_enum_old" USING "type"::"text"::"public"."special_events_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."special_events_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."special_events_type_enum_old" RENAME TO "special_events_type_enum"`);
        await queryRunner.query(`ALTER TABLE "user_levels" ALTER COLUMN "consistencyStreak" SET DEFAULT '{"current": 0, "longest": 0, "lastActivityDate": "2025-04-28T23:15:47.111Z"}'`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum_old" AS ENUM('achievement_unlocked', 'reward_earned', 'level_up', 'streak_milestone', 'cultural_content', 'system')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "type" TYPE "public"."notifications_type_enum_old" USING "type"::"text"::"public"."notifications_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notifications_type_enum_old" RENAME TO "notifications_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."tags_color_enum_old" AS ENUM('red', 'blue', 'green', 'yellow', 'purple', 'orange', 'pink', 'gray')`);
        await queryRunner.query(`ALTER TABLE "tags" ALTER COLUMN "color" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tags" ALTER COLUMN "color" TYPE "public"."tags_color_enum_old" USING "color"::"text"::"public"."tags_color_enum_old"`);
        await queryRunner.query(`ALTER TABLE "tags" ALTER COLUMN "color" SET DEFAULT 'gray'`);
        await queryRunner.query(`DROP TYPE "public"."tags_color_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."tags_color_enum_old" RENAME TO "tags_color_enum"`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "isLimited" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "isLimited" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."rewards_type_enum_old" AS ENUM('badge', 'points', 'achievement', 'cultural', 'experience', 'content')`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "type" TYPE "public"."rewards_type_enum_old" USING "type"::"text"::"public"."rewards_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "type" SET DEFAULT 'badge'`);
        await queryRunner.query(`DROP TYPE "public"."rewards_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."rewards_type_enum_old" RENAME TO "rewards_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."reward_type_enum_old" AS ENUM('badge', 'points', 'achievement', 'cultural', 'experience', 'content')`);
        await queryRunner.query(`ALTER TABLE "reward" ALTER COLUMN "type" TYPE "public"."reward_type_enum_old" USING "type"::"text"::"public"."reward_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."reward_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."reward_type_enum_old" RENAME TO "reward_type_enum"`);
    }

}
